// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest contains information sent during initial registration
type RegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationToken string                 `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"` // The registration token from CreateAgent
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddressV4       string                 `protobuf:"bytes,3,opt,name=ip_address_v4,json=ipAddressV4,proto3" json:"ip_address_v4,omitempty"`
	IpAddressV6       string                 `protobuf:"bytes,4,opt,name=ip_address_v6,json=ipAddressV6,proto3" json:"ip_address_v6,omitempty"`
	Platform          string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`                                      // "macOS", "Linux", "Windows"
	PlatformVersion   string                 `protobuf:"bytes,6,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"` // "15.6.1", "22.04.3"
	PlatformFamily    string                 `protobuf:"bytes,7,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`    // "darwin", "linux", "windows"
	Architecture      string                 `protobuf:"bytes,8,opt,name=architecture,proto3" json:"architecture,omitempty"`                              // "arm64", "amd64"
	Kernel            string                 `protobuf:"bytes,9,opt,name=kernel,proto3" json:"kernel,omitempty"`                                          // "24.6.0", "5.15.0-97-generic"
	Timestamp         int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                  // Unix timestamp in seconds (for anti-replay)
	// Environment detection (added for smart metrics collection)
	EnvironmentType  string `protobuf:"bytes,11,opt,name=environment_type,json=environmentType,proto3" json:"environment_type,omitempty"`    // "physical", "physical_with_containers", "vm", "vm_with_containers", "container"
	Hypervisor       string `protobuf:"bytes,12,opt,name=hypervisor,proto3" json:"hypervisor,omitempty"`                                     // "kvm", "vmware", "virtualbox", "hyperv", "xen", "unknown" (empty if physical)
	ContainerRuntime string `protobuf:"bytes,13,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"` // "docker", "lxc", "podman", "kubernetes", "unknown" (empty if not in container)
	// Existing agent UUID (for re-registration without creating new agent)
	// If provided and exists in DB, the agent will be reactivated instead of creating a new one
	ExistingAgentUuid string `protobuf:"bytes,14,opt,name=existing_agent_uuid,json=existingAgentUuid,proto3" json:"existing_agent_uuid,omitempty"` // UUID from /var/lib/watchflare/agent.uuid (empty if first registration)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddressV4() string {
	if x != nil {
		return x.IpAddressV4
	}
	return ""
}

func (x *RegisterRequest) GetIpAddressV6() string {
	if x != nil {
		return x.IpAddressV6
	}
	return ""
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterRequest) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *RegisterRequest) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *RegisterRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RegisterRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *RegisterRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegisterRequest) GetEnvironmentType() string {
	if x != nil {
		return x.EnvironmentType
	}
	return ""
}

func (x *RegisterRequest) GetHypervisor() string {
	if x != nil {
		return x.Hypervisor
	}
	return ""
}

func (x *RegisterRequest) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *RegisterRequest) GetExistingAgentUuid() string {
	if x != nil {
		return x.ExistingAgentUuid
	}
	return ""
}

// RegisterResponse is sent back after successful registration
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`          // UUID of the server
	AgentKey      string                 `protobuf:"bytes,4,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`       // Key for authenticating future requests
	CaCert        string                 `protobuf:"bytes,5,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`             // CA certificate in PEM format for TLS verification
	ServerName    string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"` // Server name for TLS SNI verification (e.g., "watchflare-backend")
	Reactivated   bool                   `protobuf:"varint,7,opt,name=reactivated,proto3" json:"reactivated,omitempty"`                // True if existing agent was reactivated (UUID reused), false if new registration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *RegisterResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *RegisterResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterResponse) GetReactivated() bool {
	if x != nil {
		return x.Reactivated
	}
	return false
}

// HeartbeatRequest contains info sent with each heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`               // UUID of the server
	AgentKey      string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`            // Authentication key
	IpAddressV4   string                 `protobuf:"bytes,3,opt,name=ip_address_v4,json=ipAddressV4,proto3" json:"ip_address_v4,omitempty"` // Current IPv4 (may change)
	IpAddressV6   string                 `protobuf:"bytes,4,opt,name=ip_address_v6,json=ipAddressV6,proto3" json:"ip_address_v6,omitempty"` // Current IPv6 (may change)
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                         // Unix timestamp in seconds (for anti-replay)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *HeartbeatRequest) GetIpAddressV4() string {
	if x != nil {
		return x.IpAddressV4
	}
	return ""
}

func (x *HeartbeatRequest) GetIpAddressV6() string {
	if x != nil {
		return x.IpAddressV6
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse acknowledges the heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Metrics contains system performance data
type Metrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent      float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryTotalBytes     uint64                 `protobuf:"varint,2,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryAvailableBytes uint64                 `protobuf:"varint,4,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	LoadAvg_1Min         float64                `protobuf:"fixed64,5,opt,name=load_avg_1min,json=loadAvg1min,proto3" json:"load_avg_1min,omitempty"`
	LoadAvg_5Min         float64                `protobuf:"fixed64,6,opt,name=load_avg_5min,json=loadAvg5min,proto3" json:"load_avg_5min,omitempty"`
	LoadAvg_15Min        float64                `protobuf:"fixed64,7,opt,name=load_avg_15min,json=loadAvg15min,proto3" json:"load_avg_15min,omitempty"`
	DiskTotalBytes       uint64                 `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes        uint64                 `protobuf:"varint,9,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	UptimeSeconds        uint64                 `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Timestamp            int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	// Disk I/O metrics (bytes per second, computed from delta)
	DiskReadBytesPerSec  uint64 `protobuf:"varint,12,opt,name=disk_read_bytes_per_sec,json=diskReadBytesPerSec,proto3" json:"disk_read_bytes_per_sec,omitempty"`
	DiskWriteBytesPerSec uint64 `protobuf:"varint,13,opt,name=disk_write_bytes_per_sec,json=diskWriteBytesPerSec,proto3" json:"disk_write_bytes_per_sec,omitempty"`
	// Network metrics (bytes per second, computed from delta)
	NetworkRxBytesPerSec uint64 `protobuf:"varint,14,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3" json:"network_rx_bytes_per_sec,omitempty"`
	NetworkTxBytesPerSec uint64 `protobuf:"varint,15,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3" json:"network_tx_bytes_per_sec,omitempty"`
	// Temperature (physical servers only, 0 if unavailable)
	CpuTemperatureCelsius float64 `protobuf:"fixed64,16,opt,name=cpu_temperature_celsius,json=cpuTemperatureCelsius,proto3" json:"cpu_temperature_celsius,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *Metrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *Metrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *Metrics) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *Metrics) GetLoadAvg_1Min() float64 {
	if x != nil {
		return x.LoadAvg_1Min
	}
	return 0
}

func (x *Metrics) GetLoadAvg_5Min() float64 {
	if x != nil {
		return x.LoadAvg_5Min
	}
	return 0
}

func (x *Metrics) GetLoadAvg_15Min() float64 {
	if x != nil {
		return x.LoadAvg_15Min
	}
	return 0
}

func (x *Metrics) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *Metrics) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Metrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metrics) GetDiskReadBytesPerSec() uint64 {
	if x != nil {
		return x.DiskReadBytesPerSec
	}
	return 0
}

func (x *Metrics) GetDiskWriteBytesPerSec() uint64 {
	if x != nil {
		return x.DiskWriteBytesPerSec
	}
	return 0
}

func (x *Metrics) GetNetworkRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetNetworkTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkTxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetCpuTemperatureCelsius() float64 {
	if x != nil {
		return x.CpuTemperatureCelsius
	}
	return 0
}

// ContainerMetric contains per-container performance data
type ContainerMetric struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContainerId          string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName        string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image                string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	CpuPercent           float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryLimitBytes     uint64                 `protobuf:"varint,6,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	NetworkRxBytesPerSec uint64                 `protobuf:"varint,7,opt,name=network_rx_bytes_per_sec,json=networkRxBytesPerSec,proto3" json:"network_rx_bytes_per_sec,omitempty"`
	NetworkTxBytesPerSec uint64                 `protobuf:"varint,8,opt,name=network_tx_bytes_per_sec,json=networkTxBytesPerSec,proto3" json:"network_tx_bytes_per_sec,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ContainerMetric) Reset() {
	*x = ContainerMetric{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetric) ProtoMessage() {}

func (x *ContainerMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetric.ProtoReflect.Descriptor instead.
func (*ContainerMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerMetric) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetric) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerMetric) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerMetric) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerMetric) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ContainerMetric) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ContainerMetric) GetNetworkRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkRxBytesPerSec
	}
	return 0
}

func (x *ContainerMetric) GetNetworkTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetworkTxBytesPerSec
	}
	return 0
}

// MetricsRequest contains authentication and metrics data
type MetricsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                            // UUID of the server
	AgentKey         string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`                         // Authentication key
	Metrics          *Metrics               `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`                                           // System metrics
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // Unix timestamp in seconds (for anti-replay)
	ContainerMetrics []*ContainerMetric     `protobuf:"bytes,5,rep,name=container_metrics,json=containerMetrics,proto3" json:"container_metrics,omitempty"` // Per-container metrics (empty if no containers)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *MetricsRequest) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsRequest) GetContainerMetrics() []*ContainerMetric {
	if x != nil {
		return x.ContainerMetrics
	}
	return nil
}

// MetricsResponse acknowledges metric reception
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// BufferedMetric represents a metric stored in the WAL buffer
// This message is used for disk serialization, NOT for gRPC transport
type BufferedMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`              // UUID of the agent
	AgentKey      string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`           // Authentication key
	Metrics       *Metrics               `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`                             // System metrics
	CollectedAt   int64                  `protobuf:"varint,4,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"` // Unix timestamp when metric was collected
	RetryCount    uint32                 `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`    // Number of retry attempts (0 = first attempt)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferedMetric) Reset() {
	*x = BufferedMetric{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferedMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferedMetric) ProtoMessage() {}

func (x *BufferedMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferedMetric.ProtoReflect.Descriptor instead.
func (*BufferedMetric) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *BufferedMetric) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BufferedMetric) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *BufferedMetric) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *BufferedMetric) GetCollectedAt() int64 {
	if x != nil {
		return x.CollectedAt
	}
	return 0
}

func (x *BufferedMetric) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// DroppedMetricsReport contains information about metrics that were dropped
type DroppedMetricsReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // UUID of the agent
	AgentKey       string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`                      // Authentication key
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // Unix timestamp when report was sent
	Count          int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                                           // Number of metrics dropped
	FirstDroppedAt int64                  `protobuf:"varint,5,opt,name=first_dropped_at,json=firstDroppedAt,proto3" json:"first_dropped_at,omitempty"` // Timestamp of first dropped metric
	LastDroppedAt  int64                  `protobuf:"varint,6,opt,name=last_dropped_at,json=lastDroppedAt,proto3" json:"last_dropped_at,omitempty"`    // Timestamp of last dropped metric
	Reason         string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`                                          // Reason for dropping (e.g., "max_retries_exceeded")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DroppedMetricsReport) Reset() {
	*x = DroppedMetricsReport{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedMetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedMetricsReport) ProtoMessage() {}

func (x *DroppedMetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroppedMetricsReport.ProtoReflect.Descriptor instead.
func (*DroppedMetricsReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DroppedMetricsReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DroppedMetricsReport) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *DroppedMetricsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DroppedMetricsReport) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DroppedMetricsReport) GetFirstDroppedAt() int64 {
	if x != nil {
		return x.FirstDroppedAt
	}
	return 0
}

func (x *DroppedMetricsReport) GetLastDroppedAt() int64 {
	if x != nil {
		return x.LastDroppedAt
	}
	return 0
}

func (x *DroppedMetricsReport) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DroppedMetricsResponse acknowledges the dropped metrics report
type DroppedMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroppedMetricsResponse) Reset() {
	*x = DroppedMetricsResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedMetricsResponse) ProtoMessage() {}

func (x *DroppedMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroppedMetricsResponse.ProtoReflect.Descriptor instead.
func (*DroppedMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DroppedMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DroppedMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Package represents a single installed package
type Package struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                           // Package name (e.g., "nginx", "postgresql-15")
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                     // Version string (e.g., "1.24.0-1", "15.4-1")
	Architecture   string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`                           // Architecture (e.g., "amd64", "arm64", "all")
	PackageManager string                 `protobuf:"bytes,4,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"` // Package manager type (e.g., "dpkg", "rpm", "brew")
	Source         string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                                       // Repository or source URL
	InstalledAt    int64                  `protobuf:"varint,6,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`         // Unix timestamp of installation (0 if unknown)
	PackageSize    int64                  `protobuf:"varint,7,opt,name=package_size,json=packageSize,proto3" json:"package_size,omitempty"`         // Package size in bytes
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                             // Short description (max 100 chars)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Package) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

func (x *Package) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Package) GetInstalledAt() int64 {
	if x != nil {
		return x.InstalledAt
	}
	return 0
}

func (x *Package) GetPackageSize() int64 {
	if x != nil {
		return x.PackageSize
	}
	return 0
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// PackageInventoryRequest sends package inventory (delta or full) to backend
type PackageInventoryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`    // UUID of the server
	AgentKey  string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"` // Authentication key
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Request timestamp (for anti-replay)
	// Inventory type: "delta" or "full"
	// - "delta": Only sends changes (added/removed/updated)
	// - "full": Sends complete package list (used on first run or if state corrupted)
	InventoryType string `protobuf:"bytes,4,opt,name=inventory_type,json=inventoryType,proto3" json:"inventory_type,omitempty"`
	// Delta inventory (only populated if inventory_type = "delta")
	AddedPackages   []*Package `protobuf:"bytes,5,rep,name=added_packages,json=addedPackages,proto3" json:"added_packages,omitempty"`       // Newly installed packages
	RemovedPackages []*Package `protobuf:"bytes,6,rep,name=removed_packages,json=removedPackages,proto3" json:"removed_packages,omitempty"` // Uninstalled packages
	UpdatedPackages []*Package `protobuf:"bytes,7,rep,name=updated_packages,json=updatedPackages,proto3" json:"updated_packages,omitempty"` // Packages with version changes
	// Full inventory (only populated if inventory_type = "full")
	AllPackages []*Package `protobuf:"bytes,8,rep,name=all_packages,json=allPackages,proto3" json:"all_packages,omitempty"` // Complete package list
	// Collection metadata
	CollectionDurationMs int64 `protobuf:"varint,9,opt,name=collection_duration_ms,json=collectionDurationMs,proto3" json:"collection_duration_ms,omitempty"` // Time taken to collect packages (milliseconds)
	TotalPackageCount    int32 `protobuf:"varint,10,opt,name=total_package_count,json=totalPackageCount,proto3" json:"total_package_count,omitempty"`         // Total number of packages on system
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PackageInventoryRequest) Reset() {
	*x = PackageInventoryRequest{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInventoryRequest) ProtoMessage() {}

func (x *PackageInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInventoryRequest.ProtoReflect.Descriptor instead.
func (*PackageInventoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PackageInventoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PackageInventoryRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *PackageInventoryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PackageInventoryRequest) GetInventoryType() string {
	if x != nil {
		return x.InventoryType
	}
	return ""
}

func (x *PackageInventoryRequest) GetAddedPackages() []*Package {
	if x != nil {
		return x.AddedPackages
	}
	return nil
}

func (x *PackageInventoryRequest) GetRemovedPackages() []*Package {
	if x != nil {
		return x.RemovedPackages
	}
	return nil
}

func (x *PackageInventoryRequest) GetUpdatedPackages() []*Package {
	if x != nil {
		return x.UpdatedPackages
	}
	return nil
}

func (x *PackageInventoryRequest) GetAllPackages() []*Package {
	if x != nil {
		return x.AllPackages
	}
	return nil
}

func (x *PackageInventoryRequest) GetCollectionDurationMs() int64 {
	if x != nil {
		return x.CollectionDurationMs
	}
	return 0
}

func (x *PackageInventoryRequest) GetTotalPackageCount() int32 {
	if x != nil {
		return x.TotalPackageCount
	}
	return 0
}

// PackageInventoryResponse acknowledges inventory reception
type PackageInventoryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PackagesProcessed int32                  `protobuf:"varint,3,opt,name=packages_processed,json=packagesProcessed,proto3" json:"packages_processed,omitempty"` // Number of packages processed
	ChangesDetected   int32                  `protobuf:"varint,4,opt,name=changes_detected,json=changesDetected,proto3" json:"changes_detected,omitempty"`       // Number of changes detected (added+removed+updated)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PackageInventoryResponse) Reset() {
	*x = PackageInventoryResponse{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInventoryResponse) ProtoMessage() {}

func (x *PackageInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInventoryResponse.ProtoReflect.Descriptor instead.
func (*PackageInventoryResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PackageInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PackageInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PackageInventoryResponse) GetPackagesProcessed() int32 {
	if x != nil {
		return x.PackagesProcessed
	}
	return 0
}

func (x *PackageInventoryResponse) GetChangesDetected() int32 {
	if x != nil {
		return x.ChangesDetected
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\x96\x04\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\"\n" +
	"\rip_address_v4\x18\x03 \x01(\tR\vipAddressV4\x12\"\n" +
	"\rip_address_v6\x18\x04 \x01(\tR\vipAddressV6\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\x06 \x01(\tR\x0fplatformVersion\x12'\n" +
	"\x0fplatform_family\x18\a \x01(\tR\x0eplatformFamily\x12\"\n" +
	"\farchitecture\x18\b \x01(\tR\farchitecture\x12\x16\n" +
	"\x06kernel\x18\t \x01(\tR\x06kernel\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12)\n" +
	"\x10environment_type\x18\v \x01(\tR\x0fenvironmentType\x12\x1e\n" +
	"\n" +
	"hypervisor\x18\f \x01(\tR\n" +
	"hypervisor\x12+\n" +
	"\x11container_runtime\x18\r \x01(\tR\x10containerRuntime\x12.\n" +
	"\x13existing_agent_uuid\x18\x0e \x01(\tR\x11existingAgentUuid\"\xda\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x04 \x01(\tR\bagentKey\x12\x17\n" +
	"\aca_cert\x18\x05 \x01(\tR\x06caCert\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\vreactivated\x18\a \x01(\bR\vreactivated\"\xb0\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12\"\n" +
	"\rip_address_v4\x18\x03 \x01(\tR\vipAddressV4\x12\"\n" +
	"\rip_address_v6\x18\x04 \x01(\tR\vipAddressV6\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x05\n" +
	"\aMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12,\n" +
	"\x12memory_total_bytes\x18\x02 \x01(\x04R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x124\n" +
	"\x16memory_available_bytes\x18\x04 \x01(\x04R\x14memoryAvailableBytes\x12\"\n" +
	"\rload_avg_1min\x18\x05 \x01(\x01R\vloadAvg1min\x12\"\n" +
	"\rload_avg_5min\x18\x06 \x01(\x01R\vloadAvg5min\x12$\n" +
	"\x0eload_avg_15min\x18\a \x01(\x01R\floadAvg15min\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\t \x01(\x04R\rdiskUsedBytes\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x04R\ruptimeSeconds\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x124\n" +
	"\x17disk_read_bytes_per_sec\x18\f \x01(\x04R\x13diskReadBytesPerSec\x126\n" +
	"\x18disk_write_bytes_per_sec\x18\r \x01(\x04R\x14diskWriteBytesPerSec\x126\n" +
	"\x18network_rx_bytes_per_sec\x18\x0e \x01(\x04R\x14networkRxBytesPerSec\x126\n" +
	"\x18network_tx_bytes_per_sec\x18\x0f \x01(\x04R\x14networkTxBytesPerSec\x126\n" +
	"\x17cpu_temperature_celsius\x18\x10 \x01(\x01R\x15cpuTemperatureCelsius\"\xdc\x02\n" +
	"\x0fContainerMetric\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x06 \x01(\x04R\x10memoryLimitBytes\x126\n" +
	"\x18network_rx_bytes_per_sec\x18\a \x01(\x04R\x14networkRxBytesPerSec\x126\n" +
	"\x18network_tx_bytes_per_sec\x18\b \x01(\x04R\x14networkTxBytesPerSec\"\xd5\x01\n" +
	"\x0eMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12(\n" +
	"\ametrics\x18\x03 \x01(\v2\x0e.agent.MetricsR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12C\n" +
	"\x11container_metrics\x18\x05 \x03(\v2\x16.agent.ContainerMetricR\x10containerMetrics\"E\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb6\x01\n" +
	"\x0eBufferedMetric\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12(\n" +
	"\ametrics\x18\x03 \x01(\v2\x0e.agent.MetricsR\ametrics\x12!\n" +
	"\fcollected_at\x18\x04 \x01(\x03R\vcollectedAt\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\rR\n" +
	"retryCount\"\xec\x01\n" +
	"\x14DroppedMetricsReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12(\n" +
	"\x10first_dropped_at\x18\x05 \x01(\x03R\x0efirstDroppedAt\x12&\n" +
	"\x0flast_dropped_at\x18\x06 \x01(\x03R\rlastDroppedAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"L\n" +
	"\x16DroppedMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x02\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12'\n" +
	"\x0fpackage_manager\x18\x04 \x01(\tR\x0epackageManager\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12!\n" +
	"\finstalled_at\x18\x06 \x01(\x03R\vinstalledAt\x12!\n" +
	"\fpackage_size\x18\a \x01(\x03R\vpackageSize\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xdc\x03\n" +
	"\x17PackageInventoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0einventory_type\x18\x04 \x01(\tR\rinventoryType\x125\n" +
	"\x0eadded_packages\x18\x05 \x03(\v2\x0e.agent.PackageR\raddedPackages\x129\n" +
	"\x10removed_packages\x18\x06 \x03(\v2\x0e.agent.PackageR\x0fremovedPackages\x129\n" +
	"\x10updated_packages\x18\a \x03(\v2\x0e.agent.PackageR\x0fupdatedPackages\x121\n" +
	"\fall_packages\x18\b \x03(\v2\x0e.agent.PackageR\vallPackages\x124\n" +
	"\x16collection_duration_ms\x18\t \x01(\x03R\x14collectionDurationMs\x12.\n" +
	"\x13total_package_count\x18\n" +
	" \x01(\x05R\x11totalPackageCount\"\xa8\x01\n" +
	"\x18PackageInventoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x12packages_processed\x18\x03 \x01(\x05R\x11packagesProcessed\x12)\n" +
	"\x10changes_detected\x18\x04 \x01(\x05R\x0fchangesDetected2\xfc\x02\n" +
	"\fAgentService\x12A\n" +
	"\x0eRegisterServer\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponse\x12<\n" +
	"\vSendMetrics\x12\x15.agent.MetricsRequest\x1a\x16.agent.MetricsResponse\x12R\n" +
	"\x14ReportDroppedMetrics\x12\x1b.agent.DroppedMetricsReport\x1a\x1d.agent.DroppedMetricsResponse\x12W\n" +
	"\x14SendPackageInventory\x12\x1e.agent.PackageInventoryRequest\x1a\x1f.agent.PackageInventoryResponseB\x19Z\x17watchflare/shared/protob\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: agent.RegisterRequest
	(*RegisterResponse)(nil),         // 1: agent.RegisterResponse
	(*HeartbeatRequest)(nil),         // 2: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 3: agent.HeartbeatResponse
	(*Metrics)(nil),                  // 4: agent.Metrics
	(*ContainerMetric)(nil),          // 5: agent.ContainerMetric
	(*MetricsRequest)(nil),           // 6: agent.MetricsRequest
	(*MetricsResponse)(nil),          // 7: agent.MetricsResponse
	(*BufferedMetric)(nil),           // 8: agent.BufferedMetric
	(*DroppedMetricsReport)(nil),     // 9: agent.DroppedMetricsReport
	(*DroppedMetricsResponse)(nil),   // 10: agent.DroppedMetricsResponse
	(*Package)(nil),                  // 11: agent.Package
	(*PackageInventoryRequest)(nil),  // 12: agent.PackageInventoryRequest
	(*PackageInventoryResponse)(nil), // 13: agent.PackageInventoryResponse
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: agent.MetricsRequest.metrics:type_name -> agent.Metrics
	5,  // 1: agent.MetricsRequest.container_metrics:type_name -> agent.ContainerMetric
	4,  // 2: agent.BufferedMetric.metrics:type_name -> agent.Metrics
	11, // 3: agent.PackageInventoryRequest.added_packages:type_name -> agent.Package
	11, // 4: agent.PackageInventoryRequest.removed_packages:type_name -> agent.Package
	11, // 5: agent.PackageInventoryRequest.updated_packages:type_name -> agent.Package
	11, // 6: agent.PackageInventoryRequest.all_packages:type_name -> agent.Package
	0,  // 7: agent.AgentService.RegisterServer:input_type -> agent.RegisterRequest
	2,  // 8: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	6,  // 9: agent.AgentService.SendMetrics:input_type -> agent.MetricsRequest
	9,  // 10: agent.AgentService.ReportDroppedMetrics:input_type -> agent.DroppedMetricsReport
	12, // 11: agent.AgentService.SendPackageInventory:input_type -> agent.PackageInventoryRequest
	1,  // 12: agent.AgentService.RegisterServer:output_type -> agent.RegisterResponse
	3,  // 13: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	7,  // 14: agent.AgentService.SendMetrics:output_type -> agent.MetricsResponse
	10, // 15: agent.AgentService.ReportDroppedMetrics:output_type -> agent.DroppedMetricsResponse
	13, // 16: agent.AgentService.SendPackageInventory:output_type -> agent.PackageInventoryResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
