# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchflareAgent < Formula
  desc "Watchflare server monitoring agent"
  homepage "https://watchflare.io"
  version "0.28.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.28.0/watchflare-agent_0.28.0_darwin_amd64.tar.gz"
      sha256 "37578bf25ad25e0341d4c9ec535e07fe04f07a8ab06f7517cc34d4064b6c2d3d"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.28.0/watchflare-agent_0.28.0_darwin_arm64.tar.gz"
      sha256 "976ad01fb1f31b6c94ec8341c259e1e86289137e22b1c58dfa93830a14159bbf"

      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.28.0/watchflare-agent_0.28.0_linux_amd64.tar.gz"
      sha256 "492a84d559df726f3fdab451948fc29c28445f582be33a87710822d2e7337a31"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kilian-Pichard/watchflare/releases/download/v0.28.0/watchflare-agent_0.28.0_linux_arm64.tar.gz"
      sha256 "fe27f412f0351c33701263f9c3b784f019627296a031a02fdadd56cbe746b7a8"
      define_method(:install) do
        bin.install "watchflare-agent"
        (bin/"watchflare-agent-launcher").write <<~EOS
          #!/bin/bash
          export WATCHFLARE_CONFIG_DIR="#{etc}/watchflare"
          export WATCHFLARE_DATA_DIR="#{var}/watchflare"
          exec #{bin}/watchflare-agent "$@"
        EOS
        (bin/"watchflare-agent-launcher").chmod 0755
      end
    end
  end

  def caveats
    <<~EOS
      Register your agent before starting the service:
        watchflare-agent-launcher register --token=YOUR_TOKEN --host=YOUR_HOST

      Then start the service:
        brew services start watchflare-agent

      To update:
        brew upgrade watchflare-agent && brew services restart watchflare-agent
    EOS
  end

  service do
    run ["#{bin}/watchflare-agent-launcher"]
    log_path "#{var}/log/watchflare-agent.log"
    error_log_path "#{var}/log/watchflare-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
